# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j7xelte-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/bcm4343A0_V0071.0262.hcd:system/vendor/firmware/bcm4343A0_V0071.0262.hcd \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/bcm43438A1_V0051.0220.hcd:system/vendor/firmware/bcm43438A1_V0051.0220.hcd \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/setfile_3l2.bin:system/vendor/firmware/setfile_3l2.bin \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/setfile_3p3.bin:system/vendor/firmware/setfile_3p3.bin \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/setfile_5e3.bin:system/vendor/firmware/setfile_5e3.bin \
  vendor/samsung/j7xelte-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
  vendor/samsung/j7xelte-common/proprietary/vendor/firmware/nfc/sec_s3nrn80_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn80_firmware.bin\
  vendor/samsung/j7xelte-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
  vendor/samsung/j7xelte-common/proprietary/sbin/cbd:root/sbin/cbd \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_apsta.bin_3s:system/etc/wifi/bcmdhd_apsta.bin_3s \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_mfg.bin_3s:system/etc/wifi/bcmdhd_mfg.bin_3s \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/bcmdhd_sta.bin_3s:system/etc/wifi/bcmdhd_sta.bin_3s \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt\
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/nvram_mfg.txt_3s:system/etc/wifi/nvram_mfg.txt_3s \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
  vendor/samsung/j7xelte-common/proprietary/etc/wifi/nvram_net.txt_3s:system/etc/wifi/nvram_net.txt_3s \
  vendor/samsung/j7xelte-common/proprietary/etc/nfc/sec_s3nrn80_rfreg.bin:system/etc/nfc/sec_s3nrn80_rfreg.bin \
  vendor/samsung/j7xelte-common/proprietary/etc/lhd.conf:system/etc/lhd.conf \
  vendor/samsung/j7xelte-common/proprietary/bin/rild:system/bin/rild \
  vendor/samsung/j7xelte-common/proprietary/bin/gps.cer:system/bin/gps.cer \
  vendor/samsung/j7xelte-common/proprietary/bin/gpsd:system/bin/gpsd \
  vendor/samsung/j7xelte-common/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
  vendor/samsung/j7xelte-common/proprietary/bin/lhd:system/bin/lhd \
  vendor/samsung/j7xelte-common/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
  vendor/samsung/j7xelte-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
  vendor/samsung/j7xelte-common/proprietary/lib/hw/camera.exynos5.so:system/lib/hw/camera.exynos5.so \
  vendor/samsung/j7xelte-common/proprietary/lib/hw/nfc_nci.universal7870.so:system/lib/hw/nfc_nci.universal7870.so \
  vendor/samsung/j7xelte-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
  vendor/samsung/j7xelte-common/proprietary/lib/hw/sensors.universal7870.so:system/lib/hw/sensors.universal7870.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libcsc.so:system/lib/libcsc.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libion.so:system/lib/libion.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
  vendor/samsung/j7xelte-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so
  
